controller_list:
  - name: fake_LeftArm_controller
    joints:
      - L_SHOULDER_P
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - L_ELBOW_P
      - L_ELBOW_Y
      - L_WRIST_R
      - L_WRIST_Y
  - name: fake_RightArm_controller
    joints:
      - R_SHOULDER_P
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - R_ELBOW_P
      - R_ELBOW_Y
      - R_WRIST_R
      - R_WRIST_Y